# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IoT
email: dmytro@agile.in.ua
description: > # this means to ignore newlines until "baseurl:"
  Arduino related pieces of information for fast prototyping, and first experience.
  Also blog for me, to remember what was done, and what was used.
baseurl: "/IoT" # the subpath of your site, e.g. /blog
url: "http://dmytrolev.github.io" # the base hostname & protocol for your site
github_username: dmytrolev

# Build settings
markdown: kramdown
permalink: none


